
[project]
name = "MyoUser-mjlab"
dynamic = ["version"]  # Enable dynamic version
description = "Musculoskeletal environments simulated in MuJoCo"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache 2.0" }
urls = {Homepage = "https://sites.google.com/view/myosuite"}
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch",
    "torchvision",
    "omegaconf",
    "hydra-core",
    "mujoco",
    "mujoco-warp",
    "mjlab>=1.4.0",
    "ultralytics>=8.4.62",
    "h5py",
    "mujoco-scene-editor",
    "yourdfpy",
]

[project.scripts]
myo_train = "myo_core.scripts.train:main"
myo_play = "myo_core.scripts.play:main"
myo_export = "myo_core.scripts.export:main"

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[tool.uv.sources]
warp-lang = { index = "nvidia" }

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { exclude = ["myouser.agents"] } }
py-modules = []

[tool.setuptools.package-data]
"myouser_mjlab" = ["**/*"]
