from .vr_controller_task_config_resolver import register_target_resolver
from .vr_controller_task_config import VrControllerTaskConfig
from .vr_controller_task_component import VrControllerTaskComponent